language: python
sudo: require
python:
- '3.4'
- '3.6'
services:
- docker
env:
  global:
    - secure: "VW6RiljWr8u9iPrYDncxkK0nGx3DD3lYMCBJzpybIvDLX6fOz59IFgk4OnqKBPm3ZQOFbZacWl1UshxdU+qHTnJU5tolOhLl6VGwHy5AohS3b42gpiYxKq4uuE6Wi5JQzCrPQg/Qn7g2Ru97E0dVA3eG3nJ/L2jeLopzXb9Uo5nPd0iKqdBSX/09oHcmjVyalB/FSRsspPsQ9JV/6nGk/4WcJcoD4MNZwTeDDHg77vvJ953f8c6xE/LtikClhmWnpfzk83I8SIXTWLgLflRU33MeJaAQ2/WyP9GREUtH/5Wm4vhQv0T2Hlp7wWltenNkDng+ly4hS4IWn4RoLP8eloljgr1DrjL7z/8+qvMrcKaEZugQFsPD/4E93TB42ulG6CvfCBT5k4z5LDAmDBuNREjymk2NyXwGMdsZS6IJwShp9mWFjjckQ3vlYTbUAq/1NFaM0IYxqXhaoydWU0kqJAmfQZE05eBegFpLL5Ndm2K6Pv3fEIaijy4AbVWlJjAO2gQz+kljTcnp4wNbvJC0jj8cgw/6MkdZKFifmQU8ANSmmfr9ZifdoQC5st7eWciTpGL2LjbcYsg6GfRXXUbzrfuFp3TVAi9Dg9ug8X4DrHUxG73YrezlbRA1ybhtGUfKKR81qQt09sbYtGAIWylcRdp7HY16iwuEeucvz65/hC0="
    - secure: "Yp4pLV0/6Dz6uIAsGBMBLCQFDncD3heR5PnHbLBeBQikybvy/HiIW9rqHy8EQNgDQjQWLP09bYuTecjZiOb/Ut0NbCeGNzZtUz6NCiG64d0pIxdhczpant/Sn5jAgJ+7zbhHeZe/aH9UnDZ2njc85ii4wPvqQs84dcy4gRZwFGUBzDYDvOlMt+ZU5cyqvZrGaQazWXHJ+eyTgiSKTgl9kI5CUtVjegyDw/FhYg9kTKeow9RwWrzhjwD8dhutgFM/7BWH4rdfjIlelRNUdW+xKy0m5aMf8YoABavTpoFTuWhHLDMC5AGXVtSn5YZwlU6ADpugkc308SkQu6KOvtp7B3OikjANK5VUaDTgGfUzoHRqXzayTXYYpaQe0y+0wfKpAAXW3M8l3nTJ+DdNcwtfB0YIgPrAHdd/asVo+S8dN3j6+LG4hSvHBXAx0/sauC9RJ11P/TTbev6eLGI0KZJpqshEaMvFR7SpgSVZ/sRv54fG8H2x4HlBwncuqSzqdVYm8roVz5yxxgASd+L3LKDI2BkIGN/tbbUYb6hl75oyE5u1qVGpdnGnyeK5nBCJL+W8zJvQv97+k1MbDRop2LjztlPffU70QGYmyM8LfqJWH5ccuCo5AiFw/9srYPgM+UPlaRB3OIJf+t3+MGemk0NDk1+wXgmYFSIfSXryrfxxdK0="

install:
- pip install -r requirements.txt
- pip install python-coveralls
- docker build -t geizhalsbot:latest .
script:
- python -m compileall ./
- coverage run -m unittest discover -s . -v -p "*_test.py"
after_success:
- coveralls
notifications:
  email: false
before_deploy:
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
deploy:
  - provider: script
    script: 
    - curl https://rico-j.de/travis/deploy-gh.sh
    - docker tag geizhalsbot:latest $DOCKER_HUB_USERNAME/geizhalsbot:$TRAVIS_TAG
    - docker tag geizhalsbot:latest $DOCKER_HUB_USERNAME/geizhalsbot:latest
    - docker push $DOCKER_HUB_USERNAME/geizhalsbot:latest
    - docker push $DOCKER_HUB_USERNAME/geizhalsbot:$TRAVIS_TAG
    skip_cleanup: true
    on:
      branch: master
      tags: true
      python: "3.6"

  - provider: script
    script:
    - docker tag geizhalsbot:latest $DOCKER_HUB_USERNAME/geizhalsbot:dev
    - docker push $DOCKER_HUB_USERNAME/geizhalsbot:dev
    skip_cleanup: true
    on:
      branch: dev
      python: "3.6"
