language: python
sudo: require
python:
- '3.4'
- '3.6'
services:
- docker

install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- python -m compileall ./
- coverage run -m unittest discover -s . -v -p "*_test.py"
after_success:
- coveralls
- docker build -t geizhalsbot:latest .
notifications:
  email: false
deploy:
  provider: script
  script: 
  - curl https://rico-j.de/travis/deploy-gh.sh
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker tag geizhalsbot:latest $DOCKER_HUB_USERNAME/geizhalsbot:$TRAVIS_TAG
  - docker tag geizhalsbot:latest $DOCKER_HUB_USERNAME/geizhalsbot:latest
  - docker push $DOCKER_HUB_USERNAME/geizhalsbot:latest
  - docker push $DOCKER_HUB_USERNAME/geizhalsbot:$TRAVIS_TAG
  on:
    branch: master
    tags: true
env:
  global:
  - secure: K5EG/Oczl6ADLvYW1zzZMrsCmG42yKsUQBFOSWJoYIAJ5KklHmRtHRFrisEBH59R0t60CAAGBwBQS/tr65+H4Yh08S6DzNcbOpqb5CTYbw3+2ejN/P3t3LN050iYBmv+6YBVUlgGGCSC3B+3/qT3LLCl/QNWi/lAynrNpEHxiIEA6Ck2aO7/SXuKC1xhIf+oPkZ/J8pp3MqFMesoANkU8o7fQ3NH2ngAOKSZUT5rm3iXn/WOsm2crvzs8WFiJ1xmStqcjoEWPXMrq6/pCpCBjnU5L05S9Jjf6A+lqxBa0lyU5AimCSdS0ZT8vkI8x7lV60w4Kx7F6Q96DxqS2gkpeAsDoydkYFgIIVKtgxmluBG2164/Xf+Z+NTavfgfwfFgvzPe/KkCjVCHNF4+GvpljzFqNQzW04YzcmrDPC7zCHAlrPLf3zXZxlyzlK+641Jn5fZGp8JBWQrzpiOntdBQniAaHRnMjIrBeEvCn6TxZw7gYFzM0EoI9JKpfSoi8hrZFxlS522+RiVDJepdcm6ISHy9ACUeWBNz03O1k7FdqqF+t1odb9yfPQDAJc/r6wu2o71zmvy1j/nDYbepHai3ru75tD8N7ZmitxNM0jebEEQqlnHRLg1FcttWypETm7BSQGmScXZjZo5kt+2Ih0EmjTaWVJEp1ODUiA0+rj4ue5g=
  - secure: Fr0vuC7rJHTbq6T9LWtkbQjRpB/B88loCiBaGKihpNQ3pW80m7I+X+p+s3cEx9MjXTj40tiLBpjmP4XrzooQJrKq1iz+D104Oqs2c8CysY73cCUuqxPKIxiYFeWoaIG5vwyrwLAcXnta14YF453qtNcrxcKq8EBvtR+AhlMkm5WxkdAd++s69278O4p0goRJ16QvbNnU2zcO+suQGFPV8wwcrudZWq3d4sWH7QT9suvwRUAKChskFoQt2v1CjPZGjxKlFqSb3oND80O0P0mtx6jx4BAm1PUX2tYDdDUhglk6kpCWlYhVbz6/m5pNDslrt6C4bByLxsvdtCQNagwNlGDHmciM07gZAtFmqvnAX+ryvrGL4yeqJJFXzLyy7AOzXjqpA7FuIUY0fPM2u9BT341AUa2NjmB30yBdrHWGOYSt0LvTOrePbN0HOf85wbG3MwaM9R68A5hWERGLS8q3NHQryv42rOJ63hgcF20yUJW/K3YuS7UWBClDipmBuZ4pkoz3H0eMR19cYcy3CJ5LLbiKVu2DN1DwUNzexVLH7/UkT517p1h9h1teqi82+hLX9/WIDl5tqxz4GNBU3B8uUdCxi04kgLAUayN16D6vCrXe1ecAL8Wmz4DAUMx1qTDeRGgTbihaaSkhrVMLjuUYqlREUqC7tK6qUmvwaPqlh3Y=
  - secure: aoH+BLWcJsjXmzCnXhom3i138eP38gpn2IS+phrCH5ns9e5kZtkzsvdLh8Kxv8PqjmksOgSTwxgpSSCjZiiBrV9yvtaT3ueUgn7JjhCY+wfuKeInM7kTIh8A2s2pXTkhuN/ou6aM6UKX6RsXPanNpdeQPrrW2jvDNJWuEZ93+vkektGpNJXiBJNninCSoJNlqaK5WXRrAVwyWepExGyUUw/XJS9CTFQMBwFybYJA8VOAvWuZpdXauEvCem01DiKWWs+LLil4bhyfnQAsS5q4COd9h3Own2gkSVueT8wrodsaNZK9XsHllqvfY6yRZSLK4/x5DNOB1g43iNOb0VfmVM2ku3j0XaxfLAGUwAaMszG8/LF4eyn7DANzVJwNlj+MPnuSFbuWuk3HT96iAblRYOJNQ2VYBzAo3VXvnq76M/LlLp0nHVR7mAnGcz5XlJIrLqpIettoPNs9jUHkQOGlLQDylYtm/MMmN3VKvEtRqSnKtniwO5ywHbwLE9XgVYbor2GIqhfWGA0PE0aF472RuU4zJgYdNPEM6w0EjiOgnW4pWXufQXdMOK+i4nh6xhKarpPvVNqslpqF++KYFhpIbD+JG+InnJJaC6YKeyQGxriMcG5jmio9URueLd7rOOoxJgChu3R7U6PDHQgqf5L/x7i17zMq8kPInvGnQAgVK9c=
