language: python
sudo: require
python:
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - pip install python-telegram-bot --upgrade

# command to run tests
script:
  - pwd
  - python -m compileall ./
  - python -m unittest discover -s . -v -p "*_test.py"

#  pychecker doesn't work as expected for me. Until now i'm going with just syntax checking all the files.
#  - pychecker ./*.py

notifications:
  email: false

deploy:
  provider: script
  script: curl https://rico-j.de/travis/deploy-gh.sh
  on:
    branch: master
