language: python
sudo: require
python:
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - python -m compileall ./
#  - python -m unittest discover -s . -v -p "*_test.py"
  - coverage run -m unittest discover -s . -v -p "*_test.py"

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: script
  script: curl https://rico-j.de/travis/deploy-gh.sh
  on:
    branch: master
