version: "3.3"
services:
  geizhalsbot:
    container_name: ghbot
    restart: always
    volumes:
      - /path/to/logs/:/geizhalsbot/logs
      - /path/to/config.py:/geizhalsbot/config.py
    build: .
